jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python34:
        python.version: '3.4'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - bash: |
      pip install -U pip setuptools &&
        sudo PY_VERS="$PYTHON_VERSION" tools/build-manylinux-wheel.sh &&
        pip install dist/*.whl &&
        # pytest<3.8 needed before matplotlib#12154 (matplotlib<3.1).
        # sphinx needed before matplotlib#11360 (matplotlib<3.0).
        pip install 'pytest<3.8' sphinx &&
        ./tools/ensure-mpl-test-data.py
    displayName: 'Build & install'

  - bash: |
      ./run-mpl-test-suite.py --tolerance=50 --junitxml=junit/test-results.xml
    displayName: 'Test'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - bash: |
      cp dist/*.whl "$BUILD_ARTIFACTSTAGINGDIRECTORY"
    displayName: 'Copy files'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'wheels'

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python34:
        python.version: '3.4'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - bash: |
      pip install -U pip setuptools &&
        brew update >/dev/null &&
        brew install cairo ccache llvm pkg-config &&
        # CXX must be set due to weird manipulations by distutils.
        PATH="/usr/local/opt/llvm/bin:$PATH" \
          CPPFLAGS=-L/usr/local/opt/llvm/include \
          LDFLAGS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' \
          CC='ccache clang' \
          CXX='ccache clang' \
          tools/build-osx-wheel.sh &&
        pip install dist/*.whl &&
        # pytest<3.8 needed before matplotlib#12154 (matplotlib<3.1).
        # sphinx needed before matplotlib#11360 (matplotlib<3.0).
        pip install 'pytest<3.8' sphinx &&
        ./tools/ensure-mpl-test-data.py
    displayName: 'Build & install'

  - bash: |
      ./run-mpl-test-suite.py --tolerance=50 --junitxml=junit/test-results.xml
    displayName: 'Test'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - bash: |
      cp dist/*.whl "$BUILD_ARTIFACTSTAGINGDIRECTORY"
    displayName: 'Copy files'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'wheels'

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 2

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - bash: |
      python -mpip install -U pip setuptools &&
        git clone --depth 1 https://github.com/anntzer/cairocffi-windows-wheels &&
        python -mpip install --find-links cairocffi-windows-wheels --prefer-binary cairocffi &&
        python tools/build-windows-wheel.py &&
        python -mpip install dist/*.whl &&
        # pytest<3.8 needed before matplotlib#12154 (matplotlib<3.1).
        # sphinx needed before matplotlib#11360 (matplotlib<3.0).
        pip install 'pytest<3.8' sphinx &&
        python tools/ensure-mpl-test-data.py
    displayName: 'Build & install'

  - bash: |
      python run-mpl-test-suite.py --tolerance=50 --junitxml=junit/test-results.xml
    displayName: 'Test'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - bash: |
      cp dist/*.whl "$BUILD_ARTIFACTSTAGINGDIRECTORY"
    displayName: 'Copy files'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'wheels'

- job: 'PublishWheels'
  dependsOn:
  - Linux
  - macOS
  - Windows
  condition: succeededOrFailed()

  steps:

  - checkout: none

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: 'wheels'
